const sampleListings = [
    {
        _id: 'sample1',
        title: "Cozy Beachfront Cottage",
        description: "Escape to this charming beachfront cottage for a relaxing getaway.",
        image: { url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
        price: 1500,
        location: "Malibu",
        country: "United States",
    },
    {
        _id: 'sample2',
        title: "Modern Loft in Downtown",
        description: "Stay in the heart of the city in this stylish loft apartment.",
        image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
        price: 1200,
        location: "New York City",
        country: "United States",
    },
    {
        _id: 'sample3',
        title: "Mountain Retreat",
        description: "Unplug and unwind in this peaceful mountain cabin.",
        image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
        price: 1000,
        location: "Aspen",
        country: "United States",
    },
    {
        _id: 'sample4',
        title: "Historic Villa in Tuscany",
        description: "Experience the charm of Tuscany in this beautifully restored villa.",
        image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
        price: 2500,
        location: "Florence",
        country: "Italy",
    },
    {
        _id: 'sample5',
        title: "Secluded Treehouse Getaway",
        description: "Live among the treetops in this unique treehouse retreat.",
        image: { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
        price: 800,
        location: "Portland",
        country: "United States",
    },
    {
        _id: 'sample6',
        title: "Beachfront Paradise",
        description: "Step out of your door onto the sandy beach.",
        image: { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
        price: 2000,
        location: "Cancun",
        country: "Mexico",
    },
];

module.exports = sampleListings;
